function [] = plot_parameters_skyline(parameters, version_name, model, outcome_encoding, figures_dir)

%% set important variables
 

color_dict = load_my_colors();

% set figure settings shared by all plots here
x_label = '';
my_title = '';
x_ref_input = NaN;
dot_size = 6;
sem_bar_width = 8;
highlight_connected_lines_in_dominant_direction = 0;
my_linewidth = 1; %0.65;
position_units = "centimeters";
%axis_inner_position = [1.3, 1.3, 4, 7];
figure_position_all_parameters = [0, 0, 9, 6.75]; %[0, 0, 8, 6]; 
font_size = 8*1.33333368888898; % to get fontsize 8 in Inkscape
star_font_size = 12*1.33333368888898;  % to get fontsize 12 in Inkscape
font = 'Arial'; % Arial % Times
violin_width = 1; %


% prepare main data: the parameters
if iscell(parameters)
    params = parameters{model};
else
    params = parameters;
end

%% specific plotting code for each model
switch model            
    case 1
        % my_modelsInfo{1}.paramNames = ["beta1", "lr1", "lr2"]; 
        model = 1
        mean(params)    
        

        % -------------------- plot for model 1 param -------------------- 
        scaling_factor = 100;
        f = tiledlayout(1,3,'TileSpacing','tight');
        % ---- plot beta ----
        nexttile(f,1)
        subject_mean = params(:,1) ; % should be vectors of size (n_participants,n_parameters) 
        real_yinterval = [0:2:8];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 1;
        violin_colors_in_order = color_dict.grey;
        y_label = ""; 
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);                      
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % plot the two learning rates
        nexttile(f,2,[1 2]);
        subject_mean = params(:,2:3) ; % should be vectors of size (n_participants,n_parameters)  
        % call my_skylineplot()
        type = 2;
        violin_colors_in_order = [color_dict.blue_autumn_palette ; color_dict.red_autumn_palette];
        ymin = 0;
        ymax = 1;
        y_label = "";
        x_tick_label = ''; % ["{\alpha}_{con}"; "{\alpha}_{dis}"];
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);
    
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        % figure settings
        set(gcf,'Units',position_units,'Position',figure_position_all_parameters);
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % save plot -- can adapt PNG vs SVG output directly
        name = sprintf('Parameters_model%i_%s_outcomes_%s',model,outcome_encoding,version_name);
        svnm = fullfile(figures_dir,name);
        set(gcf, 'Renderer', 'painters');
        print(gcf,[svnm,'.svg'],'-dsvg'); % print(gcf,[svnm,'.png'],'-dpng') 
        %saveas(gcf, [svnm,'.fig']);
        clear subject_mean name svnm f             

    case 2
        % my_modelsInfo{2}.paramNames = ["beta1" "a1" "b1" "a2" "b2"] ;
        model = 2
        mean(params)    
        
        % -------------------- plot for model 2 param - ADAPTED FOR SVG OUTPUT --------------------  
        % time required to export .svg file is exponentially proportional to the figure's range of y values (why?!), so exporting plot with y in [0,1] takes much less time than plot with y in [-10,10], which takes much less time than plot with y in [-40,40]
        % so must rescale y values so that they are smaller, and then replace rescaled y axis tick labels by the real ones
        % for example, for b parameter, rescale by 100, so that rescaled min and max will be -40/100 and 40/100, and then replace these tick marks by -40 and 40
        scaling_factor = 100;
        f = tiledlayout(1,5,'TileSpacing','tight');
        % ---- plot beta ----
        nexttile(f,1)
        subject_mean = params(:,1) ; % should be vectors of size (n_participants,n_parameters) 
        real_yinterval = [0:2:8];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 1;
        violin_colors_in_order = color_dict.grey;
        y_label = ""; 
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            violin_width=violin_width);   
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % ---- plot the a values ----
        nexttile(f,2,[1,2])
        subject_mean = params(:,[2,4]) ; % should be vectors of size (n_participants,n_parameters) 
        real_yinterval =  [-10:5:10];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 2; 
        violin_colors_in_order = [color_dict.blue_autumn_palette ; color_dict.red_autumn_palette];
        y_label = "";
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);  
        yline(0.0,":");
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % ---- plot the b values ----
        nexttile(f,4,[1 2]);
        subject_mean = params(:,[3,5]) ; % should be vectors of size (n_participants,n_parameters)
        real_yinterval = [-40:20:40];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 2;
        violin_colors_in_order = [color_dict.blue_autumn_palette ; color_dict.red_autumn_palette];
        y_label = "";
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);         
        yline(0.0,":");
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        % ---- whole figure settings ----
        set(gcf,'Units',position_units,'Position',figure_position_all_parameters);
        % ---- save plot ----
        name = sprintf('Parameters_model%i_%s_outcomes_%s',model,outcome_encoding,version_name);
        svnm = fullfile(figures_dir,name);
        set(gcf, 'Renderer', 'painters');
        print(gcf,[svnm,'.svg'],'-dsvg') % print(gcf,[svnm,'.png'],'-dpng') 
        %saveas(gcf, [svnm,'.fig']);
        clear subject_mean name svnm f    
        
        clear params
        clf('reset')      

    case 4
        % my_modelsInfo{4}.paramNames = ["beta0" "w" "a1" "b1" "a2" "b2" ]; 
        model = 4
        
        mean(params)

        % -------------------- plot for model 4 param - ADAPTED FOR SVG OUTPUT --------------------  
        % time required to export .svg file is exponentially proportional to the figure's range of y values (why?!), so exporting plot with y in [0,1] takes much less time than plot with y in [-10,10], which takes much less time than plot with y in [-40,40]
        % so must rescale y values so that they are smaller, and then replace rescaled y axis tick labels by the real ones
        % for example, for b parameter, rescale by 100, so that rescaled min and max will be -40/100 and 40/100, and then replace these tick marks by -40 and 40
        scaling_factor = 100;
        f = tiledlayout(1,6,'TileSpacing','tight');
        % plot beta and w
        nexttile(f,1,[1,2])
        subject_mean = params(:,[1:2]) ; % should be vectors of size (n_participants,n_parameters)  
        real_yinterval = [0:10:40]; % [0:5:max(subject_mean,[],"all")+1];     
        % rescale y values   
        subject_mean = subject_mean/scaling_factor;
        ymin = 0; %min(real_yinterval)/scaling_factor;
        ymax = 0.4; % max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 1;
        violin_colors_in_order = [color_dict.grey ; color_dict.grey];
        y_label = ""; 
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);   
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % ---- plot the a values ----
        nexttile(f,3,[1,2])
        subject_mean = params(:,[3,5]) ; % should be vectors of size (n_participants,n_parameters)  
        real_yinterval =  [-10:5:10];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 2; 
        violin_colors_in_order = [color_dict.blue_autumn_palette ; color_dict.red_autumn_palette];
        y_label = "";
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);  
        yline(0.0,":");
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % ---- plot the b values ----
        nexttile(f,5,[1 2]);
        subject_mean = params(:,[4,6]) ; % should be vectors of size (n_participants,n_parameters)  
        real_yinterval = [-40:20:40];
        % rescale y values
        subject_mean = subject_mean/scaling_factor;
        ymin = min(real_yinterval)/scaling_factor;
        ymax = max(real_yinterval)/scaling_factor;
        % call my_skylineplot()
        type = 2;
        violin_colors_in_order = [color_dict.blue_autumn_palette ; color_dict.red_autumn_palette];
        y_label = "";
        x_tick_label = ''; 
        my_skylineplot(type, subject_mean', ...
                            Colors=violin_colors_in_order, ...
                            YLim=[ymin ymax], ...
                            xRefInput=x_ref_input, ...
                            font_size=font_size, ...
                            Title=my_title, ...
                            LabelX=x_label, ...
                            LabelY=y_label, ...
                            x_tick_labels=x_tick_label, ...
                            dot_size=dot_size, ...
                            sem_bar_width=sem_bar_width, ...
                            line_width=my_linewidth, ...
                            highlight_connected_lines_in_dominant_direction=highlight_connected_lines_in_dominant_direction, ...
                            font=font, ...
                            star_font_size=star_font_size,...
                            violin_width=violin_width);  
        yline(0.0,":");
        clear subject_mean type violin_colors_in_order ymin ymax y_label x_tick_label
        hold on
        % replace rescaled y tick labels by real y tick labels
        yticks(real_yinterval/scaling_factor)
        yticklabels(string(real_yinterval))
        ax = gca;                 
        ax.XAxis.Visible = 'off'; % hides bottom x-axis (ticks, labels, and axis line)
        hold on
        % ---- whole figure settings ----
        % set font before the rest so that it applies to all subsequent items
        set(gcf,'Units',position_units,'Position',figure_position_all_parameters);
        % ---- save plot ----
        name = sprintf('Parameters_model%i_%s_outcomes_%s',model,outcome_encoding,version_name);
        svnm = fullfile(figures_dir,name);
        set(gcf, 'Renderer', 'painters');
        print(gcf,[svnm,'.svg'],'-dsvg') % print(gcf,[svnm,'.png'],'-dpng') 
        %saveas(gcf, [svnm,'.fig']);
        clear subject_mean name svnm f 
       
        clf('reset') 

end

end